# Main tasks for Home Assistant OS role

- name: Check if VM already exists
  community.libvirt.virt:
    command: list_vms
    uri: "qemu:///system"
  register: existing_vms
  changed_when: false

- name: Create and setup HAOS VM if not exists
  when: vm_name not in existing_vms.list_vms
  block:

    - name: Setup nginx reverse proxy for HAOS
      include_tasks: ../nginx/tasks/add_service.yml
      vars:
        service_name: haos
        service_config_path: "{{ role_path }}/files/haos.conf"

    - name: Setup libvirt network for HAOS VM
      include_tasks: ../qemu/tasks/setup_network.yml

    - name: Check if image already exists
      stat:
        path: "{{ images_dir }}/{{ image_filename | regex_replace('\\.xz$', '') }}"
      register: image_file

    - name: Download image if not present
      when: not image_file.stat.exists
      block:

        - name: Download HAOS image
          get_url:
            url: "{{ image_url }}"
            dest: "{{ images_dir }}/{{ image_filename }}"
            mode: '0644'

        - name: Extract image if compressed
          command:
            cmd: "unxz {{ images_dir }}/{{ image_filename }}"
          when: image_filename.endswith('.xz')
          register: unxz_result
          changed_when: unxz_result.rc == 0
        
        - name: Set proper permissions on HAOS image
          file:
            path: "{{ images_dir }}/{{ image_filename | regex_replace('\\.xz$', '') }}"
            owner: libvirt-qemu
            group: kvm
            mode: '0640'

    - name: Set final image path
      set_fact:
        vm_image: "{{ images_dir }}/{{ image_filename | regex_replace('\\.xz$', '') }}"

    - name: Create VM using qemu role
      include_tasks: ../../qemu/tasks/setup_new_vm.yml

    - name: Configure HAOS after VM creation
      include_tasks: configure_haos.yml
