services:
  ansible:
    image: alpine/ansible:latest
    container_name: ansible
    volumes:
      - ../../ansible:/ansible
      - ${USERPROFILE}/.ssh:/root/.ssh
      - ${USERPROFILE}/.ssh/known_hosts:/root/.ssh/known_hosts
    working_dir: /ansible
    environment:
      - ANSIBLE_CONFIG=/ansible/ansible.cfg
    networks:
      - ansible-net
    stdin_open: true
    tty: true
    command: /bin/sh

networks:
  ansible-net: