- name: Check if {{ network_name }} network exists
  community.libvirt.virt_net:
    command: list_nets
  register: libvirt_networks

- name: Define {{ network_name }} network if missing
  community.libvirt.virt_net:
    command: define
    name: "{{ network_name }}"
    xml: "{{ lookup('template', 'vm_network.xml.j2') }}"
  when: "network_name not in libvirt_networks.list_nets"

- name: Start {{ network_name }} network
  community.libvirt.virt_net:
    state: active
    name: "{{ network_name }}"

- name: Enable autostart for {{ network_name }} network
  community.libvirt.virt_net:
    autostart: yes
    name: "{{ network_name }}"