services:
  klipper:
    image: mkuf/klipper:latest
    container_name: klipper
    privileged: true
    volumes:
      - /home/rpi/printer_data/config/printer.cfg:/opt/printer_data/config/printer.cfg
      - /home/rpi/printer_data/config/macros.cfg:/opt/printer_data/config/macros.cfg
      - /dev:/dev
    networks: 
      - klipper-net
    restart: unless-stopped

  moonraker:
    image: mkuf/moonraker:latest
    container_name: moonraker
    privileged: true
    depends_on:
      - klipper
    ports:
      - "7125:7125"
    volumes:
      - /home/rpi/printer_data/config/moonraker.conf:/opt/printer_data/config/moonraker.conf
    networks: 
      - klipper-net
    restart: unless-stopped

  fluidd:
    image: cadriel/fluidd:latest
    container_name: fluidd
    depends_on:
      - moonraker
    ports:
      - "8080:80"
    networks: 
      - klipper-net
    restart: unless-stopped

networks:
  klipper-net:  
    driver: bridge