services:
  klipper:
    image: mkuf/klipper:latest
    container_name: klipper
    privileged: true
    volumes:
      - ~/printer-data/config:/printer_data/config
      - /dev:/dev
    networks: 
      - klipper-net
    restart: unless-stopped

  moonraker:
    image: mkuf/moonraker:latest
    container_name: moonraker
    privileged: true
    depends_on:
      - klipper
    ports:
      - "7125:7125"
    volumes:
      - ~/printer-data/config:/opt/printer_data/config
    networks: 
      - klipper-net
    restart: unless-stopped

  fluidd:
    image: cadriel/fluidd:latest
    container_name: fluidd
    depends_on:
      - moonraker
    ports:
      - "8080:80"
    volumes:
      - ~/printer-data/config:/printer_data/config
    networks: 
      - klipper-net
    restart: unless-stopped

networks:
  klipper-net:  
    driver: bridge