- name: Setup Raspberry Pi for virtualization
  hosts: localhost
  become: yes

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Chcek and install docker
      include_role:
        name: docker
        tasks_from: check.yml

    - name: check and install QEMU/libvirt
      include_role:
        name: qemu
        tasks_from: check.yml

