    - name: Ensure service network exists
      community.docker.docker_network:
        name: "{{ service-name }}-net"
        state: present
    
    - name: Connect nginx container to network
      community.docker.docker_network:
        name: "{{ service-name }}-net"
        connected:
          - nginx

    - name: Copy {{ service_name }}.conf into nginx directory
      ansible.builtin.copy:
        src: "{{ service_config_path }}"
        dest: /opt/nginx/conf.d/{{ service_name }}.conf
        mode: '0644'

    - name: Reload nginx to apply config
      community.docker.docker_container_exec:
        container: nginx
        command: nginx -s reload