  - name: Check and install Docker
    apt:
      name: 
        - docker.io
        - docker-compose
      state: present
      
  - name: Enable and start docker service
    ansible.builtin.systemd:
      name: docker
      enabled: yes
      state: started