    - name: Install docker
      ansible.builtin.apt:
        name: docker.io
        state: present

    - name: Ensure docker service is running
      ansible.builtin.systemd:
        name: docker
        enabled: yes
        state: started

    - name: Ensure docker-compose is installed
      ansible.builtin.apt:
        name: docker-compose
        state: present