- name: run necessary roles to set up the system
  hosts: localhost
  roles:
    - role: firewall
      tags: [always]
    - role: docker
      tags: [always]
    - role: qemu
      tags: [always]
    - role: nginx
      tags: [always]
    - role: cockpit
      tags: [always]
    - role: samba
      tags: [always]
