- name: Install Samba
  apt:
    name: samba
    state: present
    update_cache: yes

- name: Install pexpect if not present
  pip:
    name: pexpect

- name: Create Samba config directory
  file:
    path: /etc/samba
    state: directory
    mode: '0755'

- name: Copy base Samba configuration
  copy:
    src: "{{ role_path }}/files/smb.conf"
    dest: /etc/samba/smb.conf
    mode: '0644'
  notify: Restart samba service

- name: Enable and start Samba service
  systemd:
    name: smbd
    enabled: yes
    state: started

- name: Check if Samba user exists
  shell: pdbedit -L | grep -q "^{{ ansible_user }}:"
  register: samba_user_exists
  changed_when: false
  failed_when: false

- name: Add ansible user to Samba
  expect: 
    command: "smbpasswd -a {{ ansible_user }}"
    responses:
      "New SMB password:": "password"
      "Retype new SMB password:": "password"
  when: samba_user_exists.rc != 0
  no_log: true

- name: Allow smb through firewall
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
    comment: 'samba ports'
  loop:
    - '445'
    - '139'
  loop_control:
    pause: 1
