- name: Install Samba
  apt:
    name: samba
    state: present
    update_cache: yes

- name: Create Samba config directory
  file:
    path: /etc/samba
    state: directory
    mode: '0755'

- name: Copy base Samba configuration
  copy:
    src: "{{ role_path }}/files/smb.conf"
    dest: /etc/samba/smb.conf
    mode: '0644'
  notify: Restart samba service

- name: Create Samba user
  shell: |
    (pdbedit -L | grep {{ samba_user_name }}) || \
    (echo '{{ samba_user_password }}'; echo '{{ samba_user_password }}') | smbpasswd -a -s {{ samba_user_name }}
  changed_when: false

- name: Enable and start Samba service
  systemd:
    name: smbd
    enabled: yes
    state: started

- name: Allow smb through firewall
  community.general.ufw:
    rule: allow
    port: 455
    proto: tcp
    comment: 'samba'
