- name: Create directory
  ansible.builtin.file:
    path: "/opt/samba"
    state: directory
    mode: '0755'

- name: Copy smb config to opt directory
  ansible.builtin.file:
    src: "{{ role_path }}/files/smb.conf"
    dest: "/opt/samba/smb.conf"
    mode: '0644'

- name: Create and start Samba container
  community.docker.docker_container:
    name: samba
    image: dockurr/samba
    state: started
    restart_policy: unless-stopped
    ports:
      - "445:445"
    volumes:
      - "/opt:/opt"
    env:
      USER: "{{ samba_user_name }}"
      PASS: "{{ samba_user_password }}"
    command: >
      sh -c "ln -sf /opt/samba/smb.conf /etc/samba/smb.conf && 
             exec smbd --foreground --no-process-group"

- name: Allow smb through firewall
  community.general.ufw:
    rule: allow
    port: 455
    proto: tcp
    comment: 'samba'
