    - name: Create and start Samba container
      community.docker.docker_container:
        name: samba
        image: dockurr/samba
        state: started
        restart_policy: unless-stopped
        ports:
          - "445:445"
        volumes:
          - "{{ role_path }}/files/smb.conf:/etc/samba/smb.conf:ro"
          - "/home/rpi/printer_data/gcodes:/gcodes"
        env:
          USER: "{{ samba_user_name }}"
          PASS: "{{ samba_user_password }}"
