- name: Create and start Samba container
  community.docker.docker_container:
    name: samba
    image: dockurr/samba
    state: started
    restart_policy: unless-stopped
    ports:
      - "445:445"
    volumes:
      - "/opt:/opt"
      - "/opt/samba/smb.conf:/etc/samba/smb.conf:ro"
    env:
      USER: "{{ samba_user_name }}"
      PASS: "{{ samba_user_password }}"

- name: Allow smb through firewall
  community.general.ufw:
    rule: allow
    port: 455
    proto: tcp
    comment: 'samba'
