- name: Create directory
  ansible.builtin.file:
    path: "/home/rpi/files/samba"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory
    mode: '0755'

- name: Copy smb config to opt directory
  ansible.builtin.copy:
    src: "{{ role_path }}/files/smb.conf"
    dest: "/home/rpi/files/samba/smb.conf"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

- name: Create and start Samba container
  community.docker.docker_container:
    name: samba
    image: dockurr/samba
    state: started
    recreate: yes
    restart_policy: unless-stopped
    ports:
      - "445:445"
    volumes:
      - /home/rpi/files:/files
    env:
      USER: "{{ samba_user_name }}"
      PASS: "{{ samba_user_password }}"

- name: Create symlink for samba config inside container
  command: docker exec samba sh -c "ln -sf /files/samba/smb.conf /etc/samba/smb.conf"
  register: symlink_result
  failed_when: symlink_result.rc != 0 and 'File exists' not in symlink_result.stderr
  notify: Restart samba

- name: Allow smb through firewall
  community.general.ufw:
    rule: allow
    port: 455
    proto: tcp
    comment: 'samba'
